const PDFDocument = require('pdfkit');

function numberValue(value) {
  const number = Number(value);
  return Number.isFinite(number) ? number : 0;
}

function money(value) {
  return `Rs. ${new Intl.NumberFormat('en-IN', { maximumFractionDigits: 2 }).format(numberValue(value))}`;
}

function dateValue(value) {
  if (!value) return 'Not set';
  const date = typeof value.toDate === 'function' ? value.toDate() : new Date(value);
  return Number.isNaN(date.getTime())
    ? 'Not set'
    : new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium' }).format(date);
}

function safeFilePart(value) {
  return String(value || 'project').replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 80);
}

function drawHeader(doc, title, reference) {
  doc.fillColor('#0f4c81').fontSize(20).font('Helvetica-Bold').text('ANT SOLAR', { align: 'center' });
  doc.fillColor('#475569').fontSize(9).font('Helvetica').text('Professional Solar Solutions', { align: 'center' });
  doc.moveDown(1);
  doc.fillColor('#0f172a').fontSize(16).font('Helvetica-Bold').text(title, { align: 'center' });
  doc.fontSize(9).font('Helvetica').fillColor('#475569').text(reference, { align: 'center' });
  doc.moveDown(1.2);
  doc.strokeColor('#cbd5e1').moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(1);
}

function section(doc, title) {
  if (doc.y > 700) doc.addPage();
  doc.fillColor('#0f172a').fontSize(11).font('Helvetica-Bold').text(title.toUpperCase());
  doc.moveDown(0.35);
}

function row(doc, label, value) {
  if (doc.y > 730) doc.addPage();
  const y = doc.y;
  doc.fillColor('#64748b').fontSize(9).font('Helvetica').text(label, 50, y, { width: 165 });
  doc.fillColor('#0f172a').font('Helvetica-Bold').text(String(value ?? 'Not set'), 215, y, { width: 330 });
  doc.moveDown(0.75);
}

function systemRows(doc, project) {
  row(doc, 'Solar panels', `${numberValue(project.panelCount)} × ${project.panel?.name || 'Solar panel'}`);
  row(doc, 'Panel category', project.panel?.panelType || project.panel?.specs?.panelType || 'Not specified');
  row(doc, 'Inverter', project.inverter?.name || 'To be confirmed');
  row(doc, 'Battery', project.battery?.selectedBattery
    ? `${numberValue(project.battery.quantity)} × ${project.battery.selectedBattery.name}`
    : 'Not required');
}

function customerRows(doc, project) {
  row(doc, 'Customer', project.customerName || 'Customer');
  row(doc, 'Email', project.customerEmail || 'Not set');
  row(doc, 'Phone', project.customerPhone || 'Not set');
  row(doc, 'Installation address', project.address || 'Not set');
}

function termsRows(doc, project) {
  row(doc, 'Quoted price', money(project.quotedPrice));
  row(doc, `Advance (${numberValue(project.advancePercentage)}%)`, money(project.advanceAmount));
  row(doc, 'Balance', money(project.balanceAmount));
}

function finalize(doc) {
  doc.moveDown(1.5);
  doc.fontSize(8).font('Helvetica').fillColor('#64748b')
    .text('This document was generated by ANT Solar. Please quote the project ID in all communication.', { align: 'center' });
}

function buildBuffer(builder) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50, info: { Author: 'ANT Solar' } });
    const chunks = [];
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    builder(doc);
    doc.end();
  });
}

async function quotationAttachment(project) {
  const buffer = await buildBuffer(doc => {
    drawHeader(doc, 'SOLAR QUOTATION', `Quotation: ${project.projectId}`);
    section(doc, 'Customer details');
    customerRows(doc, project);
    section(doc, 'Recommended system');
    systemRows(doc, project);
    section(doc, 'Commercial terms');
    termsRows(doc, project);
    row(doc, 'Quotation valid until', dateValue(new Date(Date.now() + 7 * 24 * 60 * 60 * 1000)));
    section(doc, 'Important notes');
    doc.fontSize(9).font('Helvetica').fillColor('#334155')
      .text('1. Final installation is subject to site survey confirmation.\n2. Work scheduling begins after the agreed advance is received.\n3. Any customer-approved revision supersedes earlier quotation versions.', { lineGap: 4 });
    finalize(doc);
  });
  return {
    filename: `Quotation_${safeFilePart(project.projectId)}.pdf`,
    content: buffer,
    contentType: 'application/pdf'
  };
}

async function invoiceAttachment(project) {
  const buffer = await buildBuffer(doc => {
    drawHeader(doc, 'INVOICE', `Invoice: INV-${project.projectId}`);
    section(doc, 'Bill to');
    customerRows(doc, project);
    section(doc, 'Approved solar system');
    systemRows(doc, project);
    section(doc, 'Invoice summary');
    row(doc, 'Invoice amount', money(project.quotedPrice));
    row(doc, 'Advance payable', money(project.advanceAmount));
    row(doc, 'Amount received', money(project.amountPaid));
    row(doc, 'Amount remaining', money(Math.max(0, numberValue(project.quotedPrice) - numberValue(project.amountPaid))));
    row(doc, 'Approval date', dateValue(project.approvalDate || new Date()));
    finalize(doc);
  });
  return {
    filename: `Invoice_${safeFilePart(project.projectId)}.pdf`,
    content: buffer,
    contentType: 'application/pdf'
  };
}

async function receiptAttachment(project, payment) {
  const buffer = await buildBuffer(doc => {
    drawHeader(doc, 'PAYMENT RECEIPT', `Receipt: ${payment.paymentId || project.projectId}`);
    section(doc, 'Customer and project');
    row(doc, 'Customer', project.customerName || 'Customer');
    row(doc, 'Project ID', project.projectId);
    row(doc, 'Payment date', dateValue(payment.receivedAt || payment.recordedAt || new Date()));
    section(doc, 'Payment details');
    row(doc, 'Amount received', money(payment.amount));
    row(doc, 'Payment method', payment.method || 'Not specified');
    row(doc, 'Reference', payment.reference || 'Not provided');
    row(doc, 'Total received to date', money(project.amountPaid));
    row(doc, 'Remaining project amount', money(Math.max(0, numberValue(project.quotedPrice) - numberValue(project.amountPaid))));
    finalize(doc);
  });
  return {
    filename: `Payment_Receipt_${safeFilePart(payment.paymentId || project.projectId)}.pdf`,
    content: buffer,
    contentType: 'application/pdf'
  };
}

async function attachmentForNotification(notification) {
  const project = notification.payload?.project;
  if (!project) return null;
  if (notification.type === 'status_changed' && notification.payload?.newStatus === 'quote_sent') {
    return quotationAttachment(project);
  }
  if (notification.type === 'status_changed' && notification.payload?.newStatus === 'approved') {
    return invoiceAttachment(project);
  }
  if (notification.type === 'payment_received' && notification.payload?.payment) {
    return receiptAttachment(project, notification.payload.payment);
  }
  return null;
}

module.exports = {
  attachmentForNotification,
  invoiceAttachment,
  quotationAttachment,
  receiptAttachment
};
